import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AccentColorProvider } from "@/components/AccentColorProvider";
import { QueryProvider } from "@/lib/queryClient";
import { fetchThumbOverridesForSsr } from "@/lib/thumbOverridesQuery";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // Lu ici, dans le layout racine, et pas dans chaque page : les vignettes
  // apparaissent dans le feed, la découverte, la bibliothèque, les packs et le
  // lecteur. La réponse est mise en cache par Next (voir
  // `fetchThumbOverridesForSsr`), donc cette attente n'est payée qu'une fois
  // par période de revalidation, pas à chaque requête.
  const thumbOverrides = await fetchThumbOverridesForSsr();

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <QueryProvider initialThumbOverrides={thumbOverrides}>
          <AccentColorProvider>{children}</AccentColorProvider>
        </QueryProvider>
      </body>
    </html>
  );
}
