# Generated by Django 5.2.9 on 2026-01-05 13:53

import django.core.validators
import django.db.models.deletion
import modelcluster.contrib.taggit
import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        (
            "taggit",
            "0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx",
        ),
        ("wagtailcore", "0096_referenceindex_referenceindex_source_object_and_more"),
        ("wagtailimages", "0027_image_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="BaseCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("path", models.CharField(max_length=255, unique=True)),
                ("depth", models.PositiveIntegerField()),
                ("numchild", models.PositiveIntegerField(default=0)),
                ("name", models.CharField(max_length=120, unique=True)),
                ("slug", models.SlugField(blank=True, max_length=140, unique=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="MicroArticleIndexPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("qcm", "QCM"), ("true_false", "Vrai/Faux")],
                        max_length=32,
                    ),
                ),
                ("prompt", models.CharField(max_length=500)),
                ("choices", models.JSONField(blank=True, null=True)),
                ("correct_answers", models.JSONField(blank=True, null=True)),
                ("explanation", models.TextField(blank=True)),
                (
                    "difficulty",
                    models.PositiveSmallIntegerField(
                        default=3,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                ("references", models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="CategoryClasses",
            fields=[
                (
                    "basecategory_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="content.basecategory",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Catégories classes",
            },
            bases=("content.basecategory",),
        ),
        migrations.CreateModel(
            name="CategoryMaladies",
            fields=[
                (
                    "basecategory_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="content.basecategory",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Catégories maladies",
            },
            bases=("content.basecategory",),
        ),
        migrations.CreateModel(
            name="CategoryPharmacologie",
            fields=[
                (
                    "basecategory_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="content.basecategory",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Catégories pharmacologie",
            },
            bases=("content.basecategory",),
        ),
        migrations.CreateModel(
            name="MicroArticlePage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                ("title_question", models.CharField(max_length=160)),
                (
                    "answer_express",
                    models.TextField(
                        validators=[django.core.validators.MaxLengthValidator(350)]
                    ),
                ),
                (
                    "key_points",
                    wagtail.fields.StreamField(
                        [("point", 0)],
                        block_lookup={
                            0: ("wagtail.blocks.CharBlock", (), {"max_length": 90})
                        },
                    ),
                ),
                ("takeaway", models.CharField(blank=True, max_length=140)),
                (
                    "links",
                    wagtail.fields.StreamField(
                        [("link", 5)],
                        blank=True,
                        block_lookup={
                            0: ("wagtail.blocks.CharBlock", (), {"max_length": 120}),
                            1: ("wagtail.blocks.URLBlock", (), {}),
                            2: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"max_length": 40, "required": False},
                            ),
                            3: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"max_length": 120, "required": False},
                            ),
                            4: ("wagtail.blocks.DateBlock", (), {"required": False}),
                            5: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("title", 0),
                                        ("url", 1),
                                        ("type", 2),
                                        ("source", 3),
                                        ("date", 4),
                                    ]
                                ],
                                {},
                            ),
                        },
                    ),
                ),
                (
                    "see_more",
                    wagtail.fields.StreamField(
                        [
                            ("detail", 0),
                            ("mechanism_3_steps", 3),
                            ("indications", 5),
                            ("adverse_effects", 5),
                            ("warnings", 7),
                            ("interactions", 7),
                            ("monitoring", 9),
                            ("image", 12),
                            ("references", 18),
                            ("final_summary", 19),
                        ],
                        blank=True,
                        block_lookup={
                            0: (
                                "wagtail.blocks.RichTextBlock",
                                (),
                                {
                                    "features": ["bold", "italic", "link"],
                                    "required": True,
                                },
                            ),
                            1: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"max_length": 120, "required": True},
                            ),
                            2: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"max_length": 180, "required": True},
                            ),
                            3: (
                                "wagtail.blocks.StructBlock",
                                [[("target", 1), ("action", 2), ("consequence", 2)]],
                                {},
                            ),
                            4: ("wagtail.blocks.CharBlock", (), {"max_length": 120}),
                            5: (
                                "wagtail.blocks.ListBlock",
                                (4,),
                                {"max_num": 8, "min_num": 1},
                            ),
                            6: ("wagtail.blocks.CharBlock", (), {"max_length": 140}),
                            7: (
                                "wagtail.blocks.ListBlock",
                                (6,),
                                {"max_num": 8, "min_num": 1},
                            ),
                            8: ("wagtail.blocks.CharBlock", (), {"max_length": 200}),
                            9: (
                                "wagtail.blocks.StructBlock",
                                [[("what", 6), ("why", 8)]],
                                {},
                            ),
                            10: (
                                "wagtail.images.blocks.ImageChooserBlock",
                                (),
                                {"required": True},
                            ),
                            11: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"max_length": 200, "required": False},
                            ),
                            12: (
                                "wagtail.blocks.StructBlock",
                                [[("image", 10), ("caption", 11)]],
                                {},
                            ),
                            13: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"max_length": 200, "required": True},
                            ),
                            14: ("wagtail.blocks.URLBlock", (), {"required": False}),
                            15: ("wagtail.blocks.DateBlock", (), {"required": False}),
                            16: (
                                "wagtail.documents.blocks.DocumentChooserBlock",
                                (),
                                {"required": False},
                            ),
                            17: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("title", 13),
                                        ("url", 14),
                                        ("source", 11),
                                        ("date", 15),
                                        ("document", 16),
                                    ]
                                ],
                                {},
                            ),
                            18: (
                                "wagtail.blocks.ListBlock",
                                (17,),
                                {"max_num": 8, "min_num": 1},
                            ),
                            19: ("wagtail.blocks.CharBlock", (), {"max_length": 220}),
                        },
                    ),
                ),
                (
                    "cover_image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="microarticle_covers",
                        to="wagtailimages.image",
                    ),
                ),
                (
                    "related_articles",
                    models.ManyToManyField(
                        blank=True,
                        related_name="related_to",
                        to="content.microarticlepage",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="MicroArticlePageTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "content_object",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tagged_items",
                        to="content.microarticlepage",
                    ),
                ),
                (
                    "tag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_items",
                        to="taggit.tag",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="microarticlepage",
            name="tags",
            field=modelcluster.contrib.taggit.ClusterTaggableManager(
                blank=True,
                help_text="A comma-separated list of tags.",
                through="content.MicroArticlePageTag",
                to="taggit.Tag",
                verbose_name="Tags",
            ),
        ),
        migrations.CreateModel(
            name="MicroArticleQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(blank=True, editable=False, null=True),
                ),
                (
                    "page",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="microarticle_questions",
                        to="content.microarticlepage",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="linked_microarticles",
                        to="content.question",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order"],
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="microarticlepage",
            name="categories_classes",
            field=models.ManyToManyField(
                blank=True, related_name="microarticles", to="content.categoryclasses"
            ),
        ),
        migrations.AddField(
            model_name="microarticlepage",
            name="categories_maladies",
            field=models.ManyToManyField(
                blank=True, related_name="microarticles", to="content.categorymaladies"
            ),
        ),
        migrations.AddField(
            model_name="microarticlepage",
            name="categories_pharmacologie",
            field=models.ManyToManyField(
                blank=True,
                related_name="microarticles",
                to="content.categorypharmacologie",
            ),
        ),
    ]
