# Generated by Django 5.2.9 on 2026-01-11 08:09

import django.core.validators
import django.db.models.deletion
import modelcluster.contrib.taggit
import modelcluster.fields
import wagtail.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        (
            "taggit",
            "0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx",
        ),
        ("wagtailcore", "0096_referenceindex_referenceindex_source_object_and_more"),
        ("wagtailimages", "0027_image_description"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CategoryClasses",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("path", models.CharField(max_length=255, unique=True)),
                ("depth", models.PositiveIntegerField()),
                ("numchild", models.PositiveIntegerField(default=0)),
                ("name", models.CharField(max_length=120, unique=True)),
                ("slug", models.SlugField(blank=True, max_length=140, unique=True)),
            ],
            options={
                "verbose_name_plural": "Catégories classes",
            },
        ),
        migrations.CreateModel(
            name="CategoryMaladies",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("path", models.CharField(max_length=255, unique=True)),
                ("depth", models.PositiveIntegerField()),
                ("numchild", models.PositiveIntegerField(default=0)),
                ("name", models.CharField(max_length=120, unique=True)),
                ("slug", models.SlugField(blank=True, max_length=140, unique=True)),
            ],
            options={
                "verbose_name_plural": "Catégories maladies",
            },
        ),
        migrations.CreateModel(
            name="CategoryPharmacologie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("path", models.CharField(max_length=255, unique=True)),
                ("depth", models.PositiveIntegerField()),
                ("numchild", models.PositiveIntegerField(default=0)),
                ("name", models.CharField(max_length=120, unique=True)),
                ("slug", models.SlugField(blank=True, max_length=140, unique=True)),
            ],
            options={
                "verbose_name_plural": "Catégories pharmacologie",
            },
        ),
        migrations.CreateModel(
            name="MicroArticleIndexPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("qcm", "QCM"), ("true_false", "Vrai/Faux")],
                        max_length=32,
                    ),
                ),
                ("prompt", models.CharField(max_length=500)),
                ("choices", models.JSONField(blank=True, null=True)),
                ("correct_answers", models.JSONField(blank=True, null=True)),
                ("explanation", models.TextField(blank=True)),
                (
                    "difficulty",
                    models.PositiveSmallIntegerField(
                        default=3,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                ("references", models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Source",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "kind",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("press", "Presse professionnelle"),
                            ("institutional", "Site institutionnel"),
                            ("book", "Livre"),
                            ("article", "Article scientifique"),
                            ("other", "Autre"),
                        ],
                        max_length=32,
                    ),
                ),
                ("url", models.URLField(blank=True)),
                ("publisher", models.CharField(blank=True, max_length=200)),
                ("author", models.CharField(blank=True, max_length=200)),
                ("publication_date", models.DateField(blank=True, null=True)),
                ("accessed_date", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="MicroArticlePage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                ("title_question", models.CharField(max_length=160)),
                (
                    "answer_express",
                    wagtail.fields.RichTextField(
                        blank=True,
                        help_text="Réponse courte recommandée (~350 caractères), non bloquante. RichText autorisé (gras/italique/liens/listes).",
                    ),
                ),
                (
                    "answer_detail",
                    wagtail.fields.RichTextField(
                        blank=True,
                        help_text="Réponse longue optionnelle pour approfondir (RichText).",
                        null=True,
                    ),
                ),
                (
                    "key_points",
                    wagtail.fields.StreamField(
                        [("point", 0)],
                        blank=True,
                        block_lookup={
                            0: ("wagtail.blocks.CharBlock", (), {"max_length": 90})
                        },
                    ),
                ),
                (
                    "sources",
                    wagtail.fields.StreamField(
                        [("reference", 4)],
                        blank=True,
                        block_lookup={
                            0: (
                                "wagtail.snippets.blocks.SnippetChooserBlock",
                                ("content.Source",),
                                {"required": True},
                            ),
                            1: (
                                "wagtail.blocks.TextBlock",
                                (),
                                {
                                    "help_text": "Contexte ou citation courte",
                                    "required": False,
                                },
                            ),
                            2: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "Page/chapitre",
                                    "max_length": 60,
                                    "required": False,
                                },
                            ),
                            3: (
                                "wagtail.documents.blocks.DocumentChooserBlock",
                                (),
                                {"required": False},
                            ),
                            4: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("source", 0),
                                        ("note", 1),
                                        ("page", 2),
                                        ("document", 3),
                                    ]
                                ],
                                {},
                            ),
                        },
                        help_text="Sources principales de l’article",
                    ),
                ),
                (
                    "takeaway",
                    wagtail.fields.RichTextField(
                        blank=True,
                        help_text="Résumé essentiel (peut contenir gras/italique/liens/listes).",
                    ),
                ),
                (
                    "links",
                    wagtail.fields.StreamField(
                        [("link", 5)],
                        blank=True,
                        block_lookup={
                            0: ("wagtail.blocks.CharBlock", (), {"max_length": 120}),
                            1: ("wagtail.blocks.URLBlock", (), {}),
                            2: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"max_length": 40, "required": False},
                            ),
                            3: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"max_length": 120, "required": False},
                            ),
                            4: ("wagtail.blocks.DateBlock", (), {"required": False}),
                            5: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("title", 0),
                                        ("url", 1),
                                        ("type", 2),
                                        ("source", 3),
                                        ("date", 4),
                                    ]
                                ],
                                {},
                            ),
                        },
                    ),
                ),
                (
                    "see_more",
                    wagtail.fields.StreamField(
                        [
                            ("detail", 0),
                            ("mechanism_3_steps", 3),
                            ("indications", 5),
                            ("adverse_effects", 5),
                            ("warnings", 7),
                            ("interactions", 7),
                            ("monitoring", 9),
                            ("image", 12),
                            ("references", 18),
                            ("final_summary", 19),
                        ],
                        blank=True,
                        block_lookup={
                            0: (
                                "wagtail.blocks.RichTextBlock",
                                (),
                                {
                                    "features": ["bold", "italic", "link"],
                                    "required": True,
                                },
                            ),
                            1: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"max_length": 120, "required": True},
                            ),
                            2: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"max_length": 180, "required": True},
                            ),
                            3: (
                                "wagtail.blocks.StructBlock",
                                [[("target", 1), ("action", 2), ("consequence", 2)]],
                                {},
                            ),
                            4: ("wagtail.blocks.CharBlock", (), {"max_length": 120}),
                            5: (
                                "wagtail.blocks.ListBlock",
                                (4,),
                                {"max_num": 8, "min_num": 1},
                            ),
                            6: ("wagtail.blocks.CharBlock", (), {"max_length": 140}),
                            7: (
                                "wagtail.blocks.ListBlock",
                                (6,),
                                {"max_num": 8, "min_num": 1},
                            ),
                            8: ("wagtail.blocks.CharBlock", (), {"max_length": 200}),
                            9: (
                                "wagtail.blocks.StructBlock",
                                [[("what", 6), ("why", 8)]],
                                {},
                            ),
                            10: (
                                "wagtail.images.blocks.ImageChooserBlock",
                                (),
                                {"required": True},
                            ),
                            11: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"max_length": 200, "required": False},
                            ),
                            12: (
                                "wagtail.blocks.StructBlock",
                                [[("image", 10), ("caption", 11)]],
                                {},
                            ),
                            13: (
                                "wagtail.snippets.blocks.SnippetChooserBlock",
                                ("content.Source",),
                                {"required": True},
                            ),
                            14: (
                                "wagtail.blocks.TextBlock",
                                (),
                                {
                                    "help_text": "Contexte ou citation courte",
                                    "required": False,
                                },
                            ),
                            15: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "Page/chapitre",
                                    "max_length": 60,
                                    "required": False,
                                },
                            ),
                            16: (
                                "wagtail.documents.blocks.DocumentChooserBlock",
                                (),
                                {"required": False},
                            ),
                            17: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("source", 13),
                                        ("note", 14),
                                        ("page", 15),
                                        ("document", 16),
                                    ]
                                ],
                                {},
                            ),
                            18: (
                                "wagtail.blocks.ListBlock",
                                (17,),
                                {"max_num": 8, "min_num": 1},
                            ),
                            19: ("wagtail.blocks.CharBlock", (), {"max_length": 220}),
                        },
                    ),
                ),
                (
                    "categories_classes",
                    modelcluster.fields.ParentalManyToManyField(
                        blank=True,
                        related_name="microarticles",
                        to="content.categoryclasses",
                    ),
                ),
                (
                    "categories_maladies",
                    modelcluster.fields.ParentalManyToManyField(
                        blank=True,
                        related_name="microarticles",
                        to="content.categorymaladies",
                    ),
                ),
                (
                    "categories_pharmacologie",
                    modelcluster.fields.ParentalManyToManyField(
                        blank=True,
                        related_name="microarticles",
                        to="content.categorypharmacologie",
                    ),
                ),
                (
                    "cover_image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="microarticle_covers",
                        to="wagtailimages.image",
                    ),
                ),
                (
                    "related_articles",
                    modelcluster.fields.ParentalManyToManyField(
                        blank=True,
                        related_name="related_to",
                        to="content.microarticlepage",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="MicroArticlePageTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "content_object",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tagged_items",
                        to="content.microarticlepage",
                    ),
                ),
                (
                    "tag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_items",
                        to="taggit.tag",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="microarticlepage",
            name="tags",
            field=modelcluster.contrib.taggit.ClusterTaggableManager(
                blank=True,
                help_text="A comma-separated list of tags.",
                through="content.MicroArticlePageTag",
                to="taggit.Tag",
                verbose_name="Tags",
            ),
        ),
        migrations.CreateModel(
            name="MicroArticleQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(blank=True, editable=False, null=True),
                ),
                (
                    "page",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="microarticle_questions",
                        to="content.microarticlepage",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="linked_microarticles",
                        to="content.question",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SavedMicroArticle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "microarticle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saved_by",
                        to="content.microarticlepage",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saved_microarticles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["user", "created_at"],
                        name="content_sav_user_id_5546aa_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "microarticle"),
                        name="uniq_saved_microarticle_user_microarticle",
                    )
                ],
            },
        ),
    ]
