# Generated by Django 5.2.9 on 2026-01-06 07:34

import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="microarticlepage",
            name="answer_detail",
            field=models.TextField(
                blank=True,
                help_text="Réponse longue optionnelle pour approfondir.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="microarticlepage",
            name="answer_express",
            field=models.TextField(
                blank=True,
                help_text="Réponse courte recommandée (~350 caractères), non bloquante.",
            ),
        ),
        migrations.AlterField(
            model_name="microarticlepage",
            name="categories_classes",
            field=modelcluster.fields.ParentalManyToManyField(
                blank=True, related_name="microarticles", to="content.categoryclasses"
            ),
        ),
        migrations.AlterField(
            model_name="microarticlepage",
            name="categories_maladies",
            field=modelcluster.fields.ParentalManyToManyField(
                blank=True, related_name="microarticles", to="content.categorymaladies"
            ),
        ),
        migrations.AlterField(
            model_name="microarticlepage",
            name="categories_pharmacologie",
            field=modelcluster.fields.ParentalManyToManyField(
                blank=True,
                related_name="microarticles",
                to="content.categorypharmacologie",
            ),
        ),
        migrations.AlterField(
            model_name="microarticlepage",
            name="key_points",
            field=wagtail.fields.StreamField(
                [("point", 0)],
                blank=True,
                block_lookup={0: ("wagtail.blocks.CharBlock", (), {"max_length": 90})},
            ),
        ),
        migrations.AlterField(
            model_name="microarticlepage",
            name="related_articles",
            field=modelcluster.fields.ParentalManyToManyField(
                blank=True, related_name="related_to", to="content.microarticlepage"
            ),
        ),
    ]
