# Generated by Django 5.2.9 on 2026-01-08 07:13

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0002_microarticlepage_answer_detail_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Source",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "kind",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("press", "Presse professionnelle"),
                            ("institutional", "Site institutionnel"),
                            ("book", "Livre"),
                            ("article", "Article scientifique"),
                            ("other", "Autre"),
                        ],
                        max_length=32,
                    ),
                ),
                ("url", models.URLField(blank=True)),
                ("publisher", models.CharField(blank=True, max_length=200)),
                ("author", models.CharField(blank=True, max_length=200)),
                ("publication_date", models.DateField(blank=True, null=True)),
                ("accessed_date", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
            ],
        ),
        migrations.AlterField(
            model_name="microarticlepage",
            name="see_more",
            field=wagtail.fields.StreamField(
                [
                    ("detail", 0),
                    ("mechanism_3_steps", 3),
                    ("indications", 5),
                    ("adverse_effects", 5),
                    ("warnings", 7),
                    ("interactions", 7),
                    ("monitoring", 9),
                    ("image", 12),
                    ("references", 18),
                    ("final_summary", 19),
                ],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {"features": ["bold", "italic", "link"], "required": True},
                    ),
                    1: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"max_length": 120, "required": True},
                    ),
                    2: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"max_length": 180, "required": True},
                    ),
                    3: (
                        "wagtail.blocks.StructBlock",
                        [[("target", 1), ("action", 2), ("consequence", 2)]],
                        {},
                    ),
                    4: ("wagtail.blocks.CharBlock", (), {"max_length": 120}),
                    5: ("wagtail.blocks.ListBlock", (4,), {"max_num": 8, "min_num": 1}),
                    6: ("wagtail.blocks.CharBlock", (), {"max_length": 140}),
                    7: ("wagtail.blocks.ListBlock", (6,), {"max_num": 8, "min_num": 1}),
                    8: ("wagtail.blocks.CharBlock", (), {"max_length": 200}),
                    9: ("wagtail.blocks.StructBlock", [[("what", 6), ("why", 8)]], {}),
                    10: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"required": True},
                    ),
                    11: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"max_length": 200, "required": False},
                    ),
                    12: (
                        "wagtail.blocks.StructBlock",
                        [[("image", 10), ("caption", 11)]],
                        {},
                    ),
                    13: (
                        "wagtail.snippets.blocks.SnippetChooserBlock",
                        ("content.Source",),
                        {"required": True},
                    ),
                    14: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {"help_text": "Contexte ou citation courte", "required": False},
                    ),
                    15: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Page/chapitre",
                            "max_length": 60,
                            "required": False,
                        },
                    ),
                    16: (
                        "wagtail.documents.blocks.DocumentChooserBlock",
                        (),
                        {"required": False},
                    ),
                    17: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("source", 13),
                                ("note", 14),
                                ("page", 15),
                                ("document", 16),
                            ]
                        ],
                        {},
                    ),
                    18: (
                        "wagtail.blocks.ListBlock",
                        (17,),
                        {"max_num": 8, "min_num": 1},
                    ),
                    19: ("wagtail.blocks.CharBlock", (), {"max_length": 220}),
                },
            ),
        ),
    ]
