# Generated by Django 5.2.9 on 2026-01-08 11:54

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0003_source_alter_microarticlepage_see_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="microarticlepage",
            name="sources",
            field=wagtail.fields.StreamField(
                [("reference", 4)],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.snippets.blocks.SnippetChooserBlock",
                        ("content.Source",),
                        {"required": True},
                    ),
                    1: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {"help_text": "Contexte ou citation courte", "required": False},
                    ),
                    2: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Page/chapitre",
                            "max_length": 60,
                            "required": False,
                        },
                    ),
                    3: (
                        "wagtail.documents.blocks.DocumentChooserBlock",
                        (),
                        {"required": False},
                    ),
                    4: (
                        "wagtail.blocks.StructBlock",
                        [[("source", 0), ("note", 1), ("page", 2), ("document", 3)]],
                        {},
                    ),
                },
                help_text="Sources principales de l’article",
            ),
        ),
    ]
