# Generated by Django 5.2.9 on 2026-01-11 11:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0003_microarticlereadstate"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="microarticlereadstate",
            new_name="content_mic_user_id_2a3eff_idx",
            old_name="content_mic_user_id_a5fce3_idx",
        ),
    ]
