# Generated by Django 5.2.9 on 2026-01-10 14:37

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0004_microarticlepage_sources"),
    ]

    operations = [
        migrations.AlterField(
            model_name="microarticlepage",
            name="answer_express",
            field=wagtail.fields.RichTextField(
                blank=True,
                help_text="Réponse courte recommandée (~350 caractères), non bloquante. RichText autorisé (gras/italique/liens/listes).",
            ),
        ),
        migrations.AlterField(
            model_name="microarticlepage",
            name="takeaway",
            field=wagtail.fields.RichTextField(
                blank=True,
                help_text="Résumé essentiel (peut contenir gras/italique/liens/listes).",
            ),
        ),
    ]
