# Generated by Django 5.2.9 on 2026-01-10 14:51

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0005_alter_microarticlepage_answer_express_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="microarticlepage",
            name="answer_detail",
            field=wagtail.fields.RichTextField(
                blank=True,
                help_text="Réponse longue optionnelle pour approfondir (RichText).",
                null=True,
            ),
        ),
    ]
