# Generated by Django 5.2.9 on 2026-01-12 10:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0006_customimage_customrendition_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ImageLicense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120, unique=True)),
                ("url", models.URLField(blank=True)),
                (
                    "code",
                    models.CharField(
                        blank=True,
                        help_text="Facultatif (ex: CC-BY-4.0). Sert pour l'auto-complétion / filtres.",
                        max_length=50,
                    ),
                ),
            ],
            options={
                "verbose_name": "Licence d'image",
                "verbose_name_plural": "Licences d'image",
            },
        ),
        migrations.AddField(
            model_name="customimage",
            name="license",
            field=models.ForeignKey(
                blank=True,
                help_text="Choisir une licence préremplie (prioritaire sur le champ texte ci-dessus).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="images",
                to="content.imagelicense",
            ),
        ),
    ]
