# Generated by Django 5.2.9 on 2026-01-12 10:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0007_imagelicense_customimage_license"),
    ]

    operations = [
        migrations.AlterField(
            model_name="microarticlepage",
            name="cover_image",
            field=models.ForeignKey(
                blank=True,
                help_text="Illustration principale optionnelle (unique) affichée après la réponse courte.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="microarticle_covers",
                to="content.customimage",
                verbose_name="Illustration",
            ),
        ),
    ]
