# Generated by Django 5.2.9 on 2026-01-12 16:46

import modelcluster.fields
import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0008_alter_microarticlepage_cover_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="microarticlepage",
            name="answer_express",
            field=wagtail.fields.RichTextField(
                blank=True,
                help_text="Reponse courte optionnelle, recommandee (~350 caracteres). Compteur affiche dans l'admin Wagtail. RichText autorise (gras/italique/liens/listes).",
            ),
        ),
        migrations.AlterField(
            model_name="microarticlepage",
            name="categories_theme",
            field=modelcluster.fields.ParentalManyToManyField(
                related_name="microarticles", to="content.categorytheme"
            ),
        ),
        migrations.AlterField(
            model_name="microarticlepage",
            name="sources",
            field=wagtail.fields.StreamField(
                [("reference", 4)],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.snippets.blocks.SnippetChooserBlock",
                        ("content.Source",),
                        {"required": True},
                    ),
                    1: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {"help_text": "Contexte ou citation courte", "required": False},
                    ),
                    2: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Page/chapitre",
                            "max_length": 60,
                            "required": False,
                        },
                    ),
                    3: (
                        "wagtail.documents.blocks.DocumentChooserBlock",
                        (),
                        {"required": False},
                    ),
                    4: (
                        "wagtail.blocks.StructBlock",
                        [[("source", 0), ("note", 1), ("page", 2), ("document", 3)]],
                        {},
                    ),
                },
                help_text="Sources principales de l'article (max 5).",
            ),
        ),
    ]
