# Generated by Django 5.2.9 on 2026-01-12

from django.db import migrations, models
import django.db.models.deletion
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0009_alter_microarticlepage_answer_express_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="LandingPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                ("hero_title", models.CharField(blank=True, max_length=120)),
                ("hero_subtitle", models.TextField(blank=True)),
                (
                    "hero_bullets",
                    wagtail.fields.StreamField(
                        [("bullet", wagtail.blocks.CharBlock(max_length=90))],
                        blank=True,
                        use_json_field=True,
                    ),
                ),
                (
                    "steps",
                    wagtail.fields.StreamField(
                        [
                            (
                                "step",
                                wagtail.blocks.StructBlock(
                                    [
                                        ("title", wagtail.blocks.CharBlock(max_length=60)),
                                        ("detail", wagtail.blocks.CharBlock(max_length=140)),
                                    ]
                                ),
                            )
                        ],
                        blank=True,
                        max_num=3,
                        use_json_field=True,
                    ),
                ),
                (
                    "cards",
                    wagtail.fields.StreamField(
                        [
                            (
                                "card",
                                wagtail.blocks.StructBlock(
                                    [
                                        ("title", wagtail.blocks.CharBlock(max_length=80)),
                                        (
                                            "summary",
                                            wagtail.blocks.CharBlock(required=False, max_length=180),
                                        ),
                                        (
                                            "cta_label",
                                            wagtail.blocks.CharBlock(required=False, max_length=40),
                                        ),
                                        (
                                            "href",
                                            wagtail.blocks.CharBlock(required=False, max_length=200),
                                        ),
                                    ]
                                ),
                            )
                        ],
                        blank=True,
                        use_json_field=True,
                    ),
                ),
                ("primary_cta_label", models.CharField(blank=True, default="Commencer", max_length=40)),
                (
                    "primary_cta_target",
                    models.CharField(
                        choices=[
                            ("start", "Commencer"),
                            ("discover", "Dose du jour"),
                            ("cards", "Mes cartes"),
                            ("review", "Révision"),
                            ("quiz", "Quiz"),
                        ],
                        default="start",
                        max_length=32,
                    ),
                ),
                ("secondary_cta_label", models.CharField(blank=True, default="", max_length=40)),
                (
                    "secondary_cta_target",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", "—"),
                            ("start", "Commencer"),
                            ("discover", "Dose du jour"),
                            ("cards", "Mes cartes"),
                            ("review", "Révision"),
                            ("quiz", "Quiz"),
                        ],
                        default="",
                        max_length=32,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
    ]
