# Generated by Django 5.2.9 on 2026-01-12 17:54

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0010_landingpage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="landingpage",
            name="cards",
            field=wagtail.fields.StreamField(
                [("card", 4)],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"max_length": 80, "required": True},
                    ),
                    1: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"max_length": 180, "required": False},
                    ),
                    2: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"max_length": 40, "required": False},
                    ),
                    3: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"max_length": 200, "required": False},
                    ),
                    4: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 0), ("summary", 1), ("cta_label", 2), ("href", 3)]],
                        {},
                    ),
                },
            ),
        ),
        migrations.AlterField(
            model_name="landingpage",
            name="steps",
            field=wagtail.fields.StreamField(
                [("step", 2)],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"max_length": 60, "required": True},
                    ),
                    1: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"max_length": 140, "required": True},
                    ),
                    2: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 0), ("detail", 1)]],
                        {},
                    ),
                },
            ),
        ),
    ]
