# Generated by Django 5.2.9 on 2026-01-13 12:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0011_alter_landingpage_cards_alter_landingpage_steps"),
    ]

    operations = [
        migrations.AlterField(
            model_name="source",
            name="kind",
            field=models.CharField(
                blank=True,
                choices=[
                    ("press", "Presse professionnelle"),
                    ("institutional", "Site institutionnel"),
                    ("book", "Livre"),
                    ("article", "Article scientifique"),
                    ("thesis", "Thèse"),
                    ("lab_information", "Information laboratoire"),
                    ("other", "Autre"),
                ],
                max_length=32,
            ),
        ),
    ]
