# Generated by Django 5.2.9 on 2026-01-26 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0022_extend_pathology_thumb_override_patterns'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pack',
            fields=[
            ],
            options={
                'verbose_name': 'Pack',
                'verbose_name_plural': 'Packs',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('content.deck',),
        ),
        migrations.AlterModelOptions(
            name='deckcard',
            options={'ordering': ['sort_order', 'id']},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['prompt', 'id']},
        ),
        migrations.RenameIndex(
            model_name='userdeckprogress',
            new_name='content_use_user_id_7a5e04_idx',
            old_name='content_udp_user_deck_idx',
        ),
        migrations.RenameIndex(
            model_name='userdeckprogress',
            new_name='content_use_user_id_2ec502_idx',
            old_name='content_udp_user_last_seen_idx',
        ),
    ]
