# Generated by Django 5.2.9 on 2026-06-21 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0025_recappoint"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="decksubject",
            new_name="content_dec_deck_id_2810a9_idx",
            old_name="content_dec_deck_id_subj_idx",
        ),
        migrations.RenameIndex(
            model_name="decksubject",
            new_name="content_dec_subject_920d5b_idx",
            old_name="content_dec_subject_d2b1c3_idx",
        ),
        migrations.RenameIndex(
            model_name="subjectcard",
            new_name="content_sub_subject_8dde72_idx",
            old_name="content_sub_subject_8e5a4e_idx",
        ),
        migrations.RenameIndex(
            model_name="subjectcard",
            new_name="content_sub_microar_ccaeaa_idx",
            old_name="content_sub_microar_4f7c2a_idx",
        ),
    ]
