# Generated by Django 5.2.9 on 2026-08-16 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0026_rename_content_dec_deck_id_subj_idx_content_dec_deck_id_2810a9_idx_and_more'),
        # Le backfill doit lire les lignes avant qu'on supprime la table.
        ('learning', '0004_backfill_read_state_into_lesson_progress'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MicroArticleReadState',
        ),
    ]
