# Generated by Django 5.2.9 on 2026-08-16 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0027_delete_microarticlereadstate'),
    ]

    operations = [
        # Les données ont été basculées vers Deck/DeckCard par 0005_decks ;
        # les vues « saved » ne lisent plus que DeckCard.
        migrations.DeleteModel(
            name='SavedMicroArticle',
        ),
    ]
