# Generated by Django 5.2.9 on 2026-08-16 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0028_delete_savedmicroarticle'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorymaladies',
            name='domain',
            field=models.CharField(blank=True, choices=[('infectio', 'Infectiologie'), ('cardio', 'Cardiologie / vasculaire'), ('endocrino', 'Endocrinologie / métabolisme'), ('neuro', 'Neurologie / psychiatrie'), ('pneumo', 'Pneumologie / ORL'), ('gastro', 'Gastro-entérologie / hépatologie'), ('dermato', 'Dermatologie'), ('rhumato', 'Rhumatologie / douleur'), ('urogyneco', 'Urologie / gynécologie'), ('onco', 'Oncologie / hématologie'), ('ophtalmo', 'Ophtalmologie / stomatologie'), ('other', 'Autre')], default='', help_text='Pilote la couleur et le motif de la vignette générée. Laisser vide pour hériter du parent.', max_length=20, verbose_name='Domaine'),
        ),
    ]
