# Generated by Django 5.2.9 on 2026-08-16 13:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0030_backfill_categorymaladies_domain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pathologythumboverride',
            name='accent',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Couleur hexadécimale attendue (ex: #6D5BD0).', regex='^#(?:[0-9a-fA-F]{3}|[0-9a-fA-F]{6}|[0-9a-fA-F]{8})$')]),
        ),
        migrations.AlterField(
            model_name='pathologythumboverride',
            name='bg',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Couleur hexadécimale attendue (ex: #6D5BD0).', regex='^#(?:[0-9a-fA-F]{3}|[0-9a-fA-F]{6}|[0-9a-fA-F]{8})$')]),
        ),
    ]
