# Generated by Django 5.2.9 on 2026-01-12 08:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0001_initial"),
        ("learning", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CardSRSState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("srs_level", models.PositiveSmallIntegerField(default=1)),
                ("due_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("last_reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("reviews_count", models.PositiveIntegerField(default=0)),
                ("last_rating", models.CharField(blank=True, max_length=16)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "microarticle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="srs_states",
                        to="content.microarticlepage",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="card_srs_states",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={},
        ),
        migrations.AddConstraint(
            model_name="cardsrsstate",
            constraint=models.UniqueConstraint(
                fields=("user", "microarticle"),
                name="uniq_user_microarticle_srs",
            ),
        ),
        migrations.AddIndex(
            model_name="cardsrsstate",
            index=models.Index(fields=["user", "due_at"], name="learn_srs_user_due"),
        ),
        migrations.AddIndex(
            model_name="cardsrsstate",
            index=models.Index(fields=["microarticle"], name="learn_srs_card"),
        ),
    ]
