# Generated by Django 5.2.9 on 2026-01-12 09:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("learning", "0002_cardsrsstate"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="cardsrsstate",
            new_name="learning_ca_user_id_7d3825_idx",
            old_name="learn_srs_user_due",
        ),
        migrations.RenameIndex(
            model_name="cardsrsstate",
            new_name="learning_ca_microar_a1b8d9_idx",
            old_name="learn_srs_card",
        ),
    ]
