"""Serializers de l'app `content`, séparés entrée / sortie.

`inputs` valide les corps de requête (un serializer par endpoint), `outputs`
décrit la forme des réponses. Ce module réexporte les serializers de sortie pour
que `from ..serializers import MicroArticleListSerializer` continue de marcher ;
les serializers d'entrée s'importent depuis `.serializers.inputs`.
"""

from .outputs import (
    CategoryPayloadSerializer,
    ImagePayloadSerializer,
    MicroArticleCardField,
    MicroArticleCardSerializer,
    MicroArticleDetailSerializer,
    MicroArticleListSerializer,
    ParentRecapCardSerializer,
    RecapPointSerializer,
    StreamBlockSerializer,
    SubjectDetailCardSerializer,
    SubjectRecapCardSerializer,
    SubjectSummarySerializer,
    TagPayloadSerializer,
    image_payload,
)
from .responses import (
    AdminCardImportReportSerializer,
    AdminCardImportResultSerializer,
    AdminMicroArticleSearchResultSerializer,
    AdminPackDetailSerializer,
    AdminPackSummarySerializer,
    AdminTaxonomyNodeSerializer,
    AdminThumbOverrideSerializer,
    BulkAddResponseSerializer,
    CardDecksUpdateResponseSerializer,
    CopyDeckResponseSerializer,
    CountUpdateResponseSerializer,
    DeckCardsResponseSerializer,
    DeckMembershipSerializer,
    DeckMutationResponseSerializer,
    DeckSummarySerializer,
    DefaultDeckResponseSerializer,
    LandingPayloadSerializer,
    OfficialPackDetailSerializer,
    OfficialPackProgressSerializer,
    OfficialPackSummarySerializer,
    OkResponseSerializer,
    ReadStateMapSerializer,
    ReadStateSerializer,
    SavedStateSerializer,
    SubjectCardSerializer,
    SubjectDetailResponseSerializer,
    SubjectListItemSerializer,
    SubjectMutationResponseSerializer,
    TaxonomyResolveResponseSerializer,
    TaxonomyTreeResponseSerializer,
    ThumbOverridePublicSerializer,
)

__all__ = [
    "CategoryPayloadSerializer",
    "ImagePayloadSerializer",
    "MicroArticleCardField",
    "MicroArticleCardSerializer",
    "MicroArticleDetailSerializer",
    "MicroArticleListSerializer",
    "ParentRecapCardSerializer",
    "RecapPointSerializer",
    "StreamBlockSerializer",
    "SubjectDetailCardSerializer",
    "SubjectRecapCardSerializer",
    "SubjectSummarySerializer",
    "TagPayloadSerializer",
    "image_payload",
    "AdminCardImportReportSerializer",
    "AdminCardImportResultSerializer",
    "AdminMicroArticleSearchResultSerializer",
    "AdminPackDetailSerializer",
    "AdminPackSummarySerializer",
    "AdminTaxonomyNodeSerializer",
    "AdminThumbOverrideSerializer",
    "BulkAddResponseSerializer",
    "CardDecksUpdateResponseSerializer",
    "CopyDeckResponseSerializer",
    "CountUpdateResponseSerializer",
    "DeckCardsResponseSerializer",
    "DeckMembershipSerializer",
    "DeckMutationResponseSerializer",
    "DeckSummarySerializer",
    "DefaultDeckResponseSerializer",
    "LandingPayloadSerializer",
    "OfficialPackDetailSerializer",
    "OfficialPackProgressSerializer",
    "OfficialPackSummarySerializer",
    "OkResponseSerializer",
    "ReadStateMapSerializer",
    "ReadStateSerializer",
    "SavedStateSerializer",
    "SubjectCardSerializer",
    "SubjectDetailResponseSerializer",
    "SubjectListItemSerializer",
    "SubjectMutationResponseSerializer",
    "TaxonomyResolveResponseSerializer",
    "TaxonomyTreeResponseSerializer",
    "ThumbOverridePublicSerializer",
]
